#TODO: 代码仓库分组/代码仓库名
sonar.projectKey={{MODULE_GROUP}}/{{MODULE_NAME}}
#TODO: 代码仓库名
sonar.projectName={{MODULE_NAME}}
sonar.projectVersion=1.0

# 构建流水线会在项目根目录临时拷贝一个build.py文件，需要在此处指定排除，避免sonar将其当做项目自身的源文件，其他排除目录可逗号分隔继续添加
sonar.exclusions=**/build.py,**/devops_api.py,**/test_build.py
sonar.coverage.exclusions=src/*.js
#TODO：扫描目录（可任意指定）, web 默认 src
sonar.sources=src
sonar.tests=tests

# 指定编码
sonar.sourceEncoding=UTF-8
# 上传的扫描报告
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/ut-report.xml
# sonar.eslint.reportPaths=eslint-report.json
