apiVersion: batch/v1
kind: Job
metadata:
  name: {{REPO_GROUP}}-{{REPO_NAME}}-job
  labels:
    app.kubernetes.io/code-repo: {{REPO_GROUP}}_{{REPO_NAME}}
    app.kubernetes.io/name: {{REPO_GROUP}}_{{REPO_NAME}}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{MODULE_GROUP}}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/code-repo: {{REPO_GROUP}}_{{REPO_NAME}}
        app.kubernetes.io/name: {{REPO_GROUP}}_{{REPO_NAME}}
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: {{MODULE_GROUP}}
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: registry-secrets
      containers:
        - name: {{REPO_GROUP}}-{{REPO_NAME}}
          image: {{ REGISTRY_ADDR | default('') }}{{MODULE_GROUP}}/{{REPO_NAME}}:{{MODULE_NAME_UPPER_HYPHEN_IMAGE_TAG}}
          imagePullPolicy: IfNotPresent
          env:
            # TODO: 环境变量已统一收敛到 app.json 中，流水线会自动填充 env 和 envFrom，此处保留空标签即可
          envFrom:
            # TODO: ConfigMap 引用已统一收敛到 app.json 中，流水线会自动填充，此处保留空标签即可
          resources:
            # TODO: 资源限制已统一收敛到 app.json 的 resources 中，流水线会自动填充，此处保留空标签即可
